version: "3.9"
services:
  mongo-scholia:
    image: mongo-scholia
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment: 
        DB_CONNECTION: "mongodb://localhost:27017"