version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

  mongo-scholia:
    image: mongo-scholia
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment: 
        DB_CONNECTION: "mongodb://localhost:27017"